#!/usr/bin/env bash
# This script cleans data generated by unit tests

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

trap_failed_clean() {
  local ERROR_LOCATION="$1"
  printf '%s \033[91m[FAILED]\n== NOT CLEAN ==\033[0m\n' "${ERROR_LOCATION}"
}

clean_one_test() {
  export TEST_DIR="$1"
  (
    cd "${TEST_DIR}"
    export TEST_FILE="${TEST_DIR}/clean.sh"
    trap 'trap_failed_clean "${TEST_FILE}:$LINENO"' ERR
    # shellcheck source=unit-tests/simple-case/test.sh
    source "${TEST_FILE}"
    trap - ERR
  )
}

clean_all_tests() {
  while read -r TEST_DIR; do
    clean_one_test "${TEST_DIR}"
  done < <(find "${SCRIPT_DIR}/unit-tests" -mindepth 1 -maxdepth 1 -type d | sort)
  printf '\033[32m== CLEAN ==\033[0m\n'
}

clean_all_tests
